### ISSUE TITLE
`NO_FLUSH` window starting accumulation operations without flush call

### ISSUE THREAD

**Issue by MMukundi** [sg0/rmacxx#13]
Reproduction:
```cpp
int main(){
    // -- SNIP --
    // fill window
    win.fill(1);

    // create a vector and fill
    std::vector<int> twos(4); // 2(h) x 2(w) 
    std::fill(twos.begin(), twos.end(), 2);

    // Accumulation
    win(1, {0,0},{1,1}, SUM) << twos.data(); 
    win.flush(1);
    win.barrier();

    std::vector<int> results(4);
    win(1, {0,0},{1,1}) >> results.data(); 

    // -- SNIP --
}
```

Expected behavior:
```cpp
// 2 added from rank 1 only
results[0] == 3; // 1 + 2 
```

Observed behavior:
```cpp
// 2 Added from both ranks
results[0] == 5; // 1 + 2 + 2 
```

It is unclear if this behavior is in error, but from experience with RMACXX, where other expressions would not even begin to compute in a `NO_FLUSH` window, this may at least be a consistency issue across the API.

**Comment by sg0** [comment]
I think you meant `win(1, {0,0},{1,1}, SUM) << a.data();` where `a` contains 2 and `win` is initialized to 1. MPI is an SPMD model (all processes use the same program, but have their own data), so if you run this code with two processes and don't have a control statement, then both the processes run exactly same copy of the program, invoking `win(1, {0,0},{1,1}, SUM) << a.data();`. So, both processes end up accumulating vector `a` on process #1's window. Does this make sense @MMukundi

**Comment by MMukundi** [comment]
Ah ok, this makes sense. I think the semantics we were missing is that `win.flush(1)` completes operations from *and to* process 1. This test case did not have any assertions when written, so we were unsure if 3 or 5 was the intended result. Thank you for clarifying!
